/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author letic
 */
public class Dashboardd extends javax.swing.JFrame {

    /**
     * Creates new form Dashboardd
     */
    public Dashboardd(int tipoUsuario) {
        initComponents();
        if(tipoUsuario==1){
            matricula.setText("Alteração de Disciplinas");
            horario.setText("Notas e Faltas");
            historico.setText("Lista de Alunos");  
            btnIRA.setVisible(false);
            IRA.setVisible(false);
        }
        if(tipoUsuario==2){
            matricula.setText("Alteração de Disciplinas");
            horario.setText("Alteração de Cursos");
            historico.setText("Alteração de Professores");  
            IRA.setText("Alteração de Alunos");
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        dashboardBranca = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMatricula = new javax.swing.JPanel();
        matricula = new javax.swing.JLabel();
        btnListaDisciplinas = new javax.swing.JPanel();
        listaDisciplinas = new javax.swing.JLabel();
        btnIRA = new javax.swing.JPanel();
        IRA = new javax.swing.JLabel();
        btnHistorico = new javax.swing.JPanel();
        historico = new javax.swing.JLabel();
        btnHorario = new javax.swing.JPanel();
        horario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        fundo.setBackground(new java.awt.Color(242, 247, 251));

        dashboardBranca.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBranca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 39, 95), 2, true));

        btnPerfil.setBackground(new java.awt.Color(28, 39, 95));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Meu Perfil");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPerfilLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 23, 91));
        jLabel1.setText("Dashboard");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 160));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 160));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 160));

        btnMatricula.setBackground(new java.awt.Color(28, 39, 95));
        btnMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatriculaMouseClicked(evt);
            }
        });

        matricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matricula.setText("Matrícula");

        javax.swing.GroupLayout btnMatriculaLayout = new javax.swing.GroupLayout(btnMatricula);
        btnMatricula.setLayout(btnMatriculaLayout);
        btnMatriculaLayout.setHorizontalGroup(
            btnMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnMatriculaLayout.setVerticalGroup(
            btnMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMatriculaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnListaDisciplinas.setBackground(new java.awt.Color(28, 39, 95));
        btnListaDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaDisciplinasMouseClicked(evt);
            }
        });

        listaDisciplinas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listaDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        listaDisciplinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaDisciplinas.setText("Lista de Disciplinas");

        javax.swing.GroupLayout btnListaDisciplinasLayout = new javax.swing.GroupLayout(btnListaDisciplinas);
        btnListaDisciplinas.setLayout(btnListaDisciplinasLayout);
        btnListaDisciplinasLayout.setHorizontalGroup(
            btnListaDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        btnListaDisciplinasLayout.setVerticalGroup(
            btnListaDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDisciplinasLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(listaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        btnIRA.setBackground(new java.awt.Color(28, 39, 95));
        btnIRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIRAMouseClicked(evt);
            }
        });

        IRA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IRA.setForeground(new java.awt.Color(255, 255, 255));
        IRA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IRA.setText("Cálculo do IRA");

        javax.swing.GroupLayout btnIRALayout = new javax.swing.GroupLayout(btnIRA);
        btnIRA.setLayout(btnIRALayout);
        btnIRALayout.setHorizontalGroup(
            btnIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnIRALayout.setVerticalGroup(
            btnIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIRALayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(IRA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnHistorico.setBackground(new java.awt.Color(28, 39, 95));
        btnHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoricoMouseClicked(evt);
            }
        });

        historico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        historico.setForeground(new java.awt.Color(255, 255, 255));
        historico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historico.setText("Histórico");

        javax.swing.GroupLayout btnHistoricoLayout = new javax.swing.GroupLayout(btnHistorico);
        btnHistorico.setLayout(btnHistoricoLayout);
        btnHistoricoLayout.setHorizontalGroup(
            btnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnHistoricoLayout.setVerticalGroup(
            btnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHistoricoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(historico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnHorario.setBackground(new java.awt.Color(28, 39, 95));
        btnHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHorarioMouseClicked(evt);
            }
        });

        horario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        horario.setForeground(new java.awt.Color(255, 255, 255));
        horario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horario.setText("Horário");

        javax.swing.GroupLayout btnHorarioLayout = new javax.swing.GroupLayout(btnHorario);
        btnHorario.setLayout(btnHorarioLayout);
        btnHorarioLayout.setHorizontalGroup(
            btnHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnHorarioLayout.setVerticalGroup(
            btnHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHorarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardBrancaLayout = new javax.swing.GroupLayout(dashboardBranca);
        dashboardBranca.setLayout(dashboardBrancaLayout);
        dashboardBrancaLayout.setHorizontalGroup(
            dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardBrancaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardBrancaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(264, Short.MAX_VALUE))
                    .addGroup(dashboardBrancaLayout.createSequentialGroup()
                        .addGroup(dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListaDisciplinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIRA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
        );
        dashboardBrancaLayout.setVerticalGroup(
            dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardBrancaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dashboardBrancaLayout.createSequentialGroup()
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardBrancaLayout.createSequentialGroup()
                        .addComponent(btnListaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(dashboardBrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(dashboardBranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(dashboardBranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        new visualizacaoPerfil().setVisible(true);
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatriculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatriculaMouseClicked

    private void btnListaDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDisciplinasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaDisciplinasMouseClicked

    private void btnIRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIRAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIRAMouseClicked

    private void btnHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoricoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoMouseClicked

    private void btnHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboardd(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IRA;
    private javax.swing.JPanel btnHistorico;
    private javax.swing.JPanel btnHorario;
    private javax.swing.JPanel btnIRA;
    private javax.swing.JPanel btnListaDisciplinas;
    private javax.swing.JPanel btnMatricula;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JPanel dashboardBranca;
    private javax.swing.JPanel fundo;
    private javax.swing.JLabel historico;
    private javax.swing.JLabel horario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel listaDisciplinas;
    private javax.swing.JLabel matricula;
    // End of variables declaration//GEN-END:variables
}
