/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculoIra;
import exceptions.HoraException;
import exceptions.NomeException;
import javax.swing.JOptionPane;
import usuarios.*;

/**
 *
 * @author isinha
 */
public class CalculoIra extends javax.swing.JFrame {

    /**
     * Creates new form CalculoIra
     */
    public CalculoIra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneCalulaIra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paneTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        calcularIRA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calular IRA");
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        paneCalulaIra.setBackground(new java.awt.Color(242, 247, 251));
        paneCalulaIra.setMaximumSize(new java.awt.Dimension(1000, 700));
        paneCalulaIra.setMinimumSize(new java.awt.Dimension(1000, 700));
        paneCalulaIra.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 39, 95));
        jLabel1.setText("Calcula IRA");

        paneTexto.setBackground(new java.awt.Color(242, 247, 251));
        paneTexto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 39, 95), 2, true));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(242, 247, 251));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("I - O Índice de Rendimento Acadêmico (IRA) é o Somatório das notas multiplicado pela carga horária correspondente, dividido pelo Somatório\nde toda a carga horária, isto é, média ponderada.\nII - Quando reprovado por infrequencia ( RI ) a nota é considerada zero no calculo.\nIII - Não entram no calculo do IRA as disciplinas lançadas como: DISPENSADO, SEM CONCEITO E TRANCADO.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout paneTextoLayout = new javax.swing.GroupLayout(paneTexto);
        paneTexto.setLayout(paneTextoLayout);
        paneTextoLayout.setHorizontalGroup(
            paneTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneTextoLayout.setVerticalGroup(
            paneTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calcularIRA.setText("Calcular");
        calcularIRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularIRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCalulaIraLayout = new javax.swing.GroupLayout(paneCalulaIra);
        paneCalulaIra.setLayout(paneCalulaIraLayout);
        paneCalulaIraLayout.setHorizontalGroup(
            paneCalulaIraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCalulaIraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCalulaIraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(paneCalulaIraLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(paneCalulaIraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcularIRA)
                            .addComponent(paneTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneCalulaIraLayout.setVerticalGroup(
            paneCalulaIraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCalulaIraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(calcularIRA)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneCalulaIra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneCalulaIra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularIRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularIRAActionPerformed
        Aluno a = new Aluno();
        float ira = 0;
        try {
            ira = a.calculaIra();
        } catch (HoraException ex) {
            //Logger.getLogger(CalculoIra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NomeException ex) {
            //Logger.getLogger(CalculoIra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(rootPane, "IRA calculado: " + ira);
    }//GEN-LAST:event_calcularIRAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoIra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoIra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoIra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoIra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoIra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularIRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel paneCalulaIra;
    private javax.swing.JPanel paneTexto;
    // End of variables declaration//GEN-END:variables
}
